spring:
  application:
    name: zup_library
  datasource:
    url: jdbc:postgresql://localhost:5432/zup_library
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect